export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT'
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const CLEAR_PRODUCT_LIST = 'CLEAR_PRODUCT_LIST'
export const GET_PRODUCT_MESSAGE = 'GET_PRODUCT_MESSAGE'